### ISSUE TITLE
NA is undefined in embed version

### ISSUE THREAD

**Issue by apleshkov** [normanzb/amdshim#1]
https://github.com/normanzb/amdshim/blob/master/amdshim.embed.js#L64

**Comment by normanzb** [comment]
thanks for pointing that out, i've fixed it.
But it seems pointless to pass an anonymous module to amdshim in most case, if you merge all the modules together with r.js, they all should come with predefined 'path' as first parameter of `define()`

**Comment by apleshkov** [comment]
That's true, but [dragula.js](https://github.com/bevacqua/dragula/blob/master/dist/dragula.js) tries to define itself anonymously (the bundled version at least). I ended up including dragula before any amd stuff, so it exposes itself globally (cause it checks `if (define && define.amd) { ... }`).

Anyway I don't understand why this lib doesn't do `define('dragula.js', ...)` or smth like that.
AFAIK it's bad behaviour for an amd-compatible library.

**Comment by normanzb** [comment]
sorry for confusion this is not meant to be a fully functional amd compatible library... i built it with limited functions so that it is small enough to be bundled together with my other libs.

**Comment by apleshkov** [comment]
Oh I think your lib is ok and does the stuff, but dragula defines itself in a very strange way. Anyway thanks for the lib and fix =)
